# Generated by Django 4.2.7 on 2026-04-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_flashcard_flashcarddeck_quiz_quizquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
