# Generated by Django 4.2.7 on 2026-04-17 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_note_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cornell', 'Cornell Notes'), ('study', 'Study Guide'), ('research', 'Research Summary')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('data', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='projects.project')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
